language: java

jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer

dist: trusty
sudo: required

install: ./install_essentia.sh

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar